export const ShipmentServiceType = {
  LOCKER_STANDARD: 'LOCKER_STANDARD',
  LOCKER_PASS_THRU: 'LOCKER_PASS_THRU',
  LOCKER_ECONOMY: 'LOCKER_ECONOMY',
  LOCKER_C2C: 'LOCKER_C2C',

  COURIER_STANDARD: 'COURIER_STANDARD',
  COURIER_EXPRESS_1000: 'COURIER_EXPRESS_1000',
  COURIER_EXPRESS_1200: 'COURIER_EXPRESS_1200',
  COURIER_EXPRESS_1700: 'COURIER_EXPRESS_1700',
  COURIER_PALLET: 'COURIER_PALLET',
  COURIER_C2C: 'COURIER_C2C',
} as const;

export type ShipmentServiceType =
  (typeof ShipmentServiceType)[keyof typeof ShipmentServiceType];
