export const ShipmentStatus = {
  CREATED: 'CREATED',
  OFFERS_PREPARED: 'OFFERS_PREPARED',
  OFFER_SELECTED: 'OFFER_SELECTED',
  CONFIRMED: 'CONFIRMED',
  DISPATCHED_BY_SENDER: 'DISPATCHED_BY_SENDER',
  DISPATCHED_BY_SENDER_TO_POK: 'DISPATCHED_BY_SENDER_TO_POK',
  COLLECTED_FROM_SENDER: 'COLLECTED_FROM_SENDER',
  TAKEN_BY_COURIER: 'TAKEN_BY_COURIER',
  ADOPTED_AT_SOURCE_BRANCH: 'ADOPTED_AT_SOURCE_BRANCH',
  SENT_FROM_SOURCE_BRANCH: 'SENT_FROM_SOURCE_BRANCH',
  ADOPTED_AT_SORTING_CENTER: 'ADOPTED_AT_SORTING_CENTER',
  SENT_FROM_SORTING_CENTER: 'SENT_FROM_SORTING_CENTER',
  ADOPTED_AT_TARGET_BRANCH: 'ADOPTED_AT_TARGET_BRANCH',
  READY_TO_PICKUP: 'READY_TO_PICKUP',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  RETURNED_TO_SENDER: 'RETURNED_TO_SENDER',
  AVIZO: 'AVIZO',
  CLAIMED: 'CLAIMED',
  CANCELLED: 'CANCELLED',
} as const;

export type ShipmentStatus =
  (typeof ShipmentStatus)[keyof typeof ShipmentStatus];
