export const PointFunctionType = {
  PARCEL: 'PARCEL',
  PARCEL_SEND: 'PARCEL_SEND',
  PARCEL_COLLECT: 'PARCEL_COLLECT',
  PARCEL_REVERSE_RETURN_SEND: 'PARCEL_REVERSE_RETURN_SEND',
  STANDARD_LETTER_COLLECT: 'STANDARD_LETTER_COLLECT',
  STANDARD_LETTER_SEND: 'STANDARD_LETTER_SEND',
  ALLEGRO_PARCEL_COLLECT: 'ALLEGRO_PARCEL_COLLECT',
  ALLEGRO_PARCEL_SEND: 'ALLEGRO_PARCEL_SEND',
  ALLEGRO_PARCEL_REVERSE_RETURN_SEND: 'ALLEGRO_PARCEL_REVERSE_RETURN_SEND',
  ALLEGRO_LETTER_COLLECT: 'ALLEGRO_LETTER_COLLECT',
  ALLEGRO_LETTER_SEND: 'ALLEGRO_LETTER_SEND',
  ALLEGRO_LETTER_REVERSE_RETURN_SEND: 'ALLEGRO_LETTER_REVERSE_RETURN_SEND',
  ALLEGRO_COURIER_COLLECT: 'ALLEGRO_COURIER_COLLECT',
  ALLEGRO_COURIER_SEND: 'ALLEGRO_COURIER_SEND',
  ALLEGRO_COURIER_REVERSE_RETURN_SEND: 'ALLEGRO_COURIER_REVERSE_RETURN_SEND',
  STANDARD_COURIER_COLLECT: 'STANDARD_COURIER_COLLECT',
  STANDARD_COURIER_SEND: 'STANDARD_COURIER_SEND',
  STANDARD_COURIER_REVERSE_RETURN_SEND: 'STANDARD_COURIER_REVERSE_RETURN_SEND',
  AIR_ON_AIRPORT: 'AIR_ON_AIRPORT',
  AIR_OUTSIDE_AIRPORT: 'AIR_OUTSIDE_AIRPORT',
  COOL_PARCEL_COLLECT: 'COOL_PARCEL_COLLECT',
  LAUNDRY: 'LAUNDRY',
  AVIZO: 'AVIZO',
} as const;

export type PointFunctionType =
  (typeof PointFunctionType)[keyof typeof PointFunctionType];
